development:
  adapter: postgresql
  database: <%= ENV['WORKY_DATABASE'] %>
  host: <%= ENV['WORKY_HOST'] %>
  username: <%= ENV['WORKY_USER'] %>
  password: <%= ENV['WORKY_PASSWORD'] %>
  encoding: utf8
  port: 5432

production: &production
  adapter: postgresql
  database: <%= ENV['WORKY_DATABASE'] %>
  host: <%= ENV['WORKY_HOST'] %>
  username: <%= ENV['WORKY_USER'] %>
  password: <%= ENV['WORKY_PASSWORD'] %>
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  port: 5432

cable:
  <<: *production

queue:
  <<: *production

cache:
  <<: *production

