development:
  adapter: postgresql
  database: <%= ENV['WORKY_DATABASE'] %>
  host: <%= ENV['WORKY_HOST'] %>
  username: <%= ENV['WORKY_USER'] %>
  password: <%= ENV['WORKY_PASSWORD'] %>
  encoding: utf8
  port: 5432

production:
  adapter: postgresql
  database: <%= ENV['WORKY_DATABASE'] %>
  host: <%= ENV['WORKY_HOST'] %>
  username: <%= ENV['WORKY_USER'] %>
  password: <%= ENV['WORKY_PASSWORD'] %>
  encoding: utf8
  port: 5432
