module AiRecordsHelper
def whisper_like_languages
  [
    { code: "af", title: "Afrikaans" },
    { code: "ar", title: "Árabe" },
    { code: "hy", title: "Armênio" },
    { code: "az", title: "Azerbaijano" },
    { code: "be", title: "Bielorrusso" },
    { code: "bs", title: "Bósnio" },
    { code: "bg", title: "Búlgaro" },
    { code: "ca", title: "Catalão" },
    { code: "zh", title: "Chinês" },
    { code: "hr", title: "Croata" },
    { code: "cs", title: "Tcheco" },
    { code: "da", title: "Dinamarquês" },
    { code: "nl", title: "Holandês" },
    { code: "en", title: "Inglês" },
    { code: "et", title: "Estoniano" },
    { code: "fi", title: "Finlandês" },
    { code: "fr", title: "Francês" },
    { code: "gl", title: "Galego" },
    { code: "de", title: "Alemão" },
    { code: "el", title: "Gregp" },
    { code: "he", title: "Hebraico" },
    { code: "hi", title: "Hindi" },
    { code: "hu", title: "Húngaro" },
    { code: "is", title: "Islandês" },
    { code: "id", title: "Indonésio" },
    { code: "it", title: "Italiano" },
    { code: "ja", title: "Japonês" },
    { code: "kn", title: "Canarês" },
    { code: "kk", title: "Cazaque" },
    { code: "ko", title: "Coreano" },
    { code: "lv", title: "Letão" },
    { code: "lt", title: "Lituano" },
    { code: "mk", title: "Macedônio" },
    { code: "ms", title: "Malaio" },
    { code: "mr", title: "Marati" },
    { code: "mi", title: "Maori" },
    { code: "ne", title: "Nepali" },
    { code: "no", title: "Norueguês" },
    { code: "fa", title: "Persa" },
    { code: "pl", title: "Polonês" },
    { code: "pt", title: "Português" },
    { code: "ro", title: "Romeno" },
    { code: "ru", title: "Russo" },
    { code: "sr", title: "Sérvio" },
    { code: "sk", title: "Eslovaco" },
    { code: "sl", title: "Esloveno" },
    { code: "es", title: "Espanhol" },
    { code: "sw", title: "Suaíli" },
    { code: "sv", title: "Sueco" },
    { code: "tl", title: "Tagalo" },
    { code: "ta", title: "Tamil" },
    { code: "th", title: "Tailandês" },
    { code: "tr", title: "Turco" },
    { code: "uk", title: "Ucraniano" },
    { code: "ur", title: "Urdu" },
    { code: "vi", title: "Vietnamita" },
    { code: "cy", title: "Galês" }
  ].map { |lang| OpenStruct.new(lang) }
end
end
