apis:
  pinecone:
    metric: "cosine"
    dimensions: "1536"
    index_name: "https://baia-gj6jb7r.svc.aped-4627-b74a.pinecone.io"
    api_key: "pcsk_427qoS_TagQo3Qq248V3JJaCKUaE2cZNwZ1WuqrDEYUhk8e6tcSrXGY2bbVcxVohB3G1tG"
    namespace: "baia"
  openai:
    access_token: "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"
    admin_token: "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"
    organization_id: "org-R2SeGIu3KmWIkWolg3g06NXE"
  perplexity:
    api_key: "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"
  anthropic: 
    api_key: "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"
  xai:
    api_key: "xai-DdC7rETmsF47VOurAn5FMpfYTDQz79XOojbAjz6D8930yMn1VLJKUUk6fHk8C1mIRuMBJxC1fnSLzuLk"

